### ISSUE TITLE
bam/sam file input 

### ISSUE THREAD

**Issue by Rhia15** [sanger-tol/PretextMap#11]
Hi, just wondering, to generate the bam/sam file, do I need to go through the whole Omni-C pipeline i.e, use pairtools ect. or can I simply use one bwa mem command to get the input file? 

Any advice would be great, thank you!

**Comment by additive3** [comment]
Hi @Rhia15 
No you don have to use pipeline from Omni-C/Arima etc.

You can just align with BWA and then generate the Pretext image with the (sorted) bam output.

`bwa index my.fasta`
`bwa mem -t 8 my.fasta reads1.fq reads2.fq > align.bam`
`samtools sort -@8 -o sorted.bam align.bam`
`samtools view -@8 -h sorted.bam | PretextMap -o map.pretext`

There are reasons for using Omni-C workflow or other [readmapping](https://pipelines.tol.sanger.ac.uk/readmapping) for read trimming/dup removal etc but just BWA mapping will produce an interpretable map

**Comment by Rhia15** [comment]
Thank you!! Really appreciate the quick replies! :)
