### ISSUE TITLE
Add telomeric regions track

### ISSUE THREAD

**Issue by ksc289** [sanger-tol/PretextMap#9]
Hi :)
I have a .fasta file  with telomeric regions that I would like to add to my pretextmap. Could you tell me how can I do that?

Thank you very much,

Karen.

**Comment by additive3** [comment]
Hi Karen @ksc289 

In order to embed these information into the Pretext image please use [PretextGraph](https://github.com/sanger-tol/PretextGraph)
You will need to translate your telomeric region information into bedGraph format file.

**Comment by ksc289** [comment]
Hi @additive3 
Thank you very much, I tried in this way and it worked!
Cheers,
Karen :)
